version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"  # Mapea el puerto 9000 para acceder desde el host
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarpassword
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - sonarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 10
      start_period: 40s
      timeout: 20s
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpassword
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sonarnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 30s
      retries: 10
      start_period: 40s
      timeout: 20s
    restart: always

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  postgres-data:

networks:
  sonarnet:
    driver: bridge
